---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      hostNetwork: true
      containers:
        - name: homebridge
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.name | quote }}
          env:
            - name: TZ
              value: "Europe/Vienna"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: HOMEBRIDGE_CONFIG_UI
              value: "1"
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "8581"
          volumeMounts:
            - name: homebridge-storage
              mountPath: /homebridge
          ports:
            - containerPort: 8581
              name: ui
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "250m"
      volumes:
        - name: homebridge-storage
          persistentVolumeClaim:
            claimName: homebridge-data
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
spec:
  type: ClusterIP
  selector:
    app: homebridge
  ports:
    - name: http
      port: 8581
      targetPort: 8581
