---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: nfs-fast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeSelector:
        zigbee: "true"
      tolerations:
        - key: "zigbee"
          operator: "Equal"
          value: "only"
          effect: "NoSchedule"
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          env:
            - name: TZ
              value: Europe/Berlin
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: udev
              mountPath: /run/udev
              readOnly: true
            - name: usb
              mountPath: /dev/ttyUSB0
          ports:
            - containerPort: 8080
              name: http
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: usb
          hostPath:
            path: /dev/ttyUSB0
            type: CharDevice

---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
