apiVersion: apps/v1
kind: Deployment
metadata:
  name: libspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libspeedtest
  template:
    metadata:
      labels:
        app: libspeedtest
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: libspeedtest
        readinessProbe:
          httpGet: {path: /, port: 80}
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet: {path: /, port: 80}
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        env:
        - name: MODE
          value: "standalone"
        - name: WEBPORT
          value: "80"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: libspeedtest-svc
spec:
  type: ClusterIP
  selector:
    app: libspeedtest
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80