apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-data-upload
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 1Gi