apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.models.name | default (printf "%s-models-pvc" .Release.Name) }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- with .Values.persistence.models.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.persistence.models.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
