apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-dns
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Release.Name }}-cert
  rules:
    {{- range (prepend .Values.ingress.extraHosts .Values.domain) }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comfyui-svc
                port:
                  name: http
    {{- end }}
