apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: widefrog-{{ include "urlParamsHash" . }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
