---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
        - name: synapse
          image:  matrixdotorg/synapse:latest
          volumeMounts:
            - name: synapse-storage
              mountPath: /data
          ports:
            - containerPort: 8008
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "250m"
      volumes:
        - name: synapse-storage
          persistentVolumeClaim:
            claimName: synapse-data
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
spec:
  type: ClusterIP
  selector:
    app: synapse
  ports:
    - name: http
      port: 8008
      targetPort: 8008
