apiVersion: v1
kind: ServiceAccount
metadata:
  name: direwolf-operator
  labels:
    app: direwolf
    component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: direwolf-operator
  labels:
    app: direwolf
    component: operator
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["direwolf.games-on-whales.github.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "persistentvolumeclaims", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: direwolf-operator
  labels:
    app: direwolf
    component: operator
subjects:
- kind: ServiceAccount
  name: direwolf-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: direwolf-operator