apiVersion: apps/v1
kind: Deployment
metadata:
  name: direwolf-operator
  labels:
    app: direwolf
    component: operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: direwolf
      component: operator
  template:
    metadata:
      labels:
        app: direwolf
        component: operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - direwolf
                - key: component
                  operator: In
                  values:
                  - operator
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: direwolf-operator
      containers:
        - name: operator
          image: {{ .Values.operatorImage | default "ghcr.io/games-on-whales/operator:main" }}
          imagePullPolicy: Always
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: STORAGE_CLASS_NAME
            value: {{ .Values.sessions.storageClassName | default "nfs-fast" }}
          - name: EXTERNAL_HOSTNAME
            value: "{{ .Values.externalHostname | default "127.0.0.1" }}:47989"
          - name: WOLF_IMAGE
            value: {{ .Values.wolfImage | default "ghcr.io/games-on-whales/wolf:dev-moonlight-fixes" }}
          - name: WOLF_AGENT_IMAGE
            value: {{ .Values.wolfAgentImage | default "ghcr.io/games-on-whales/wolf-agent:main" }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi