apiVersion: v1
kind: ServiceAccount
metadata:
  name: direwolf-moonlight-proxy
  labels:
    app: direwolf
    component: direwolf-moonlight-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: direwolf-moonlight-proxy
  labels:
    app: direwolf
    component: direwolf-moonlight-proxy
rules:
- apiGroups: ["direwolf.games-on-whales.github.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["direwolf.games-on-whales.github.io"]
  resources: ["pairings", "sessions"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: direwolf-moonlight-proxy
  labels:
    app: direwolf
    component: direwolf-moonlight-proxy
subjects:
- kind: ServiceAccount
  name: direwolf-moonlight-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: direwolf-moonlight-proxy