apiVersion: v1
kind: Service
metadata:
  name: direwolf
  labels:
    app: direwolf
    component: moonlight-proxy
  annotations:
    metallb.io/allow-shared-ip: {{ .Release.Namespace }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalHostname }}
spec:
  type: LoadBalancer
  selector:
    app: direwolf
    component: moonlight-proxy
  ports:
    - name: http
      protocol: TCP
      port: 47984
    - name: https
      protocol: TCP
      port: 47989